defaults:
  - model:
      - qwen25_7b

sft:
  # tune_args:
  finetune: true
  stage: sft
  is_instruction_dataset: true
  variable_seq_lengths: false
  tokenizer_not_use_fast: true
  prompt_type: qwen

  # gpt_args:
  norm_epsilon: 1e-6
  micro_batch_size: 2
  global_batch_size: 128
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: ./Qwen2.5-7B/
  train_iters: 5000
  lr: 5e-5
  lr_decay_style: cosine
  min_lr: 1.25e-7
  lr_warmup_fraction: 0.01
  weight_decay: 1e-1
  clip_grad: 1.0
  initial_loss_scale: 4096
  use_distributed_optimizer: true
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 2
  sequence_parallel: true
  use_mcore_models: true
  use_fused_rmsnorm: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true
  seq_length: 4096
  adam_beta1: 0.9
  adam_beta2: 0.95
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  overlap_grad_reduce: true
  overlap_param_gather: true
  max_position_embeddings: 4096

  # data_args:
  data_path: ./dataset/data
  reset_position_ids: true
  split: 100,0,0
  no_shuffle: false

  # ckpt_args:
  no_load_optim: true
  no_load_rng: true
  no_save_optim: true
  no_save_rng: true
  seed: 1234
  model: qwen25_7b
  load: ./ckpt
  save: ./ckpt

  # output_args:
  log_interval: 1
  save_interval: 5000
  eval_interval: 5000
  eval_iters: 0
  log_throughput: true
