input: ./dataset/train-00000-of-00001.parquet
tokenizer_name_or_path: ./model_from_hf/qwen25-7b
output_prefix: .dataset/pe-nlp/data
handler_name: R1AlpacaStyleInstructionHandler
tokenizer_type: HuggingFaceTokenizer
workers: 8
log_interval: 1000
prompt_type: qwen
map_keys: {"prompt":"problem", "query":"", "response": "answer", "system":""}