input: ./dataset/orz.json
tokenizer_name_or_path: /data/models/Qwen2.5-7B
output_prefix: ./dataset/orz
handler_name: R1AlpacaStyleInstructionHandler
tokenizer_type: HuggingFaceTokenizer
workers: 8
log_interval: 1000
prompt_type: qwen_r1
dataset_additional_keys: [labels]
map_keys: {"prompt":"problem", "query":"", "response": "answer", "system":""}