zero3_size: 8
transformer_layers:
  - mindspeed_mm.models.predictor.dits.hunyuan_video_dit.MMDoubleStreamBlock
  - mindspeed_mm.models.predictor.dits.hunyuan_video_dit.MMSingleStreamBlock
backward_prefetch: 'BACKWARD_PRE'
param_dtype: "bf16"
reduce_dtype: "fp32"
forward_prefetch: True
limit_all_gathers: True
ignored_modules:
  - ae
  - text_encoder